# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-13 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LineHosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.CharField(max_length=20, verbose_name='\u7ebf\u8def\u540d')),
                ('host', models.CharField(max_length=6, verbose_name='\u4e3b\u673a\u540d')),
                ('status', models.CharField(max_length=20, verbose_name='\u7ebf\u8def\u72b6\u6001')),
                ('adsl_ip', models.CharField(default='', max_length=15, verbose_name='adsl\u5730\u5740')),
                ('last_update_time', models.DateTimeField(auto_now_add=True, verbose_name='\u6700\u8fd1\u66f4\u65b0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u7ebf\u8def\u4e3b\u673a\u5217\u8868',
                'verbose_name_plural': '\u7ebf\u8def\u4e3b\u673a\u5217\u8868',
            },
        ),
    ]
