# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-13 12:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LineHosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.CharField(max_length=20, verbose_name='\u7ebf\u8def\u540d')),
                ('host', models.CharField(max_length=6, verbose_name='\u4e3b\u673a\u540d')),
            ],
            options={
                'verbose_name': '\u7ebf\u8def\u4e3b\u673a\u5217\u8868',
                'verbose_name_plural': '\u7ebf\u8def\u4e3b\u673a\u5217\u8868',
            },
        ),
        migrations.CreateModel(
            name='LineStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'available'), (1, 'using'), (2, 'used'), (3, 'dailing')], verbose_name='\u7ebf\u8def\u72b6\u6001')),
                ('adsl_ip', models.CharField(default='', max_length=15, verbose_name='adsl\u5730\u5740')),
                ('last_update_time', models.DateTimeField(auto_now_add=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.LineHosts', verbose_name='\u7ebf\u8def\u540d')),
            ],
            options={
                'verbose_name': '\u7ebf\u8def\u72b6\u6001',
                'verbose_name_plural': '\u7ebf\u8def\u72b6\u6001',
            },
        ),
    ]
